services:
  - type: web
    name: the-blogs
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py seed_articles && python manage.py collectstatic --noinput"
    startCommand: "gunicorn BlogProject.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "the-blogs.onrender.com"
